[package]
name = "mdnt-groups-support"
description = "Support traits for the `picus::group` macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
repository.workspace = true
license-file.workspace = true




