[workspace]
members = ["crates/support-macros"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Daniel Dominguez (Veridise) <daniel@veridise.com>"]
edition = "2024"
rust-version = "1.85"
readme = "README.md"
repository = "https://github.com/Veridise/midnight-extractor"
license-file = "LICENSE"
