[workspace]
members = [ "crates/groups-support", "crates/support","crates/support-macros"]
resolver = "2"

[workspace.package]
version = "0.2.0"
authors = ["Daniel Dominguez (Veridise) <daniel@veridise.com>"]
edition = "2024"
rust-version = "1.85"
readme = "README.md"
repository = "https://github.com/Veridise/midnight-extractor"
license-file = "LICENSE"

[workspace.dependencies]
ff = "0.13"

[workspace.dependencies.midnight-proofs]
git = "https://github.com/midnightntwrk/midnight-zk"
default-features = false
features = [
    "bits",
    "cost-estimator",
    "circuit-params",
    "committed-instances",
    # Commented out until https://github.com/midnightntwrk/midnight-zk/pull/137 merges.
    # "region-groups"
] 

[workspace.dependencies.midnight-curves]
git = "https://github.com/midnightntwrk/midnight-zk"


[workspace.dependencies.haloumi]
git = "https://github.com/Veridise/llzk-rs"
default-features = false
features = ["picus-backend"]
package = "halo2-llzk-frontend"
branch = "dani/convenience-methods"

[workspace.dependencies.haloumi-ir]
git = "https://github.com/Veridise/llzk-rs"
default-features = false
features = ["picus-backend"]
package = "halo2-llzk-frontend"
branch = "dani/convenience-methods"

